language: python
python:
    - "3.6"

before_install:
    - sudo apt-add-repository -y ppa:ubuntugis/ubuntugis-unstable
    - sudo apt-get update
    - sudo apt-get install libgeos-dev
    - pip install --upgrade pip
    - pip install opencv-python
    - pip install shapely
    - pip install -U pytest

script:
    - cd test
    - echo "Hello tissueloc!!!"
